### ISSUE TITLE
kidash must create the .kibana index using Kibana for versions >= 6.1

### ISSUE THREAD

**Issue by acs** [chaoss/grimoirelab-kidash#20]
After Kibana 6.1 the `.kibana` index, in which all information related to index patterns, dashboards, visualization and searches is stored, it is not created by Kibana until it is needed. When Kibana creates this .kibana index it includes some templates in it in order to control how the mappings are created.

kidash for importing a dashboard load all the data in the `.kibana` index. If it does not exists, it is created by Elasticsearch with the first load of data into it by kidash. But it is not created with the templates that Kibana needs, so this `.kibana` index won't work as expected and for example, index patterns won't work.

In order to fix this issue, kidash must check if `.kibana` index exists in versions >= 6.1 and if not, it must create it, before any import. To create this index using Kibana, the Kibana REST API can be used as described by one of the Kibana core developers [here](https://discuss.elastic.co/t/kibana-6-1-wont-create-kibana-index-in-es-6-1/111755).

**Comment by jgbarah** [comment]
You can also check how that's done now. If I'm not wrong, this is the code (that you can find in the [Dockerfile for grimoirelab/full](https://github.com/chaoss/grimoirelab/blob/master/docker/Dockerfile-full)):

```
    ( until $(curl --output /dev/null --silent --fail http://127.0.0.1:9200/.kibana/config/_search ); do \
        printf '.' && \
        sleep 2 && \
        curl -XPOST "http://127.0.0.1:5601/api/kibana/settings/indexPattern:placeholder" \
          -H 'Content-Type: application/json' -H 'kbn-version: '${KB_VERSION} \
          -H 'Accept: application/json' -d '{"value": "*"}' \
          --silent --output /dev/null ; \
done )
```

Now I don't remember if we had some code in Mordred too, but that could be the case. Let me know if you need some help with this.

**Comment by acs** [comment]
Thanks @jgbarah . It seems that the way to force the creation of the `.kibana` index by Kibana is easier than that. Once the PR for fixing this issue is done, you can check it. kidash will keep the responsibility of all of that so if you are using it for panels deployment, you can just remove this code. And the same will be done in mordred.

**Comment by acs** [comment]
Already fixed in: https://github.com/chaoss/grimoirelab-kidash/pull/21
