### ISSUE TITLE
kidash==0.4.21 is not published in pypi.

### ISSUE THREAD

**Issue by xiao623** [chaoss/grimoirelab-kidash#47]
After #46, we need install kidash==0.4.21, but it is not published in Pypi.

**Comment by vchrombie** [comment]
Thanks for reporting the issue @xiao623 and sorry for the inconvenience caused.

We are integrating github action workflows which should solve this problem of packages getting outdated.

I think @sduenas can update the package manually, but I will soon be integrating the workflows to automate this problem.

**Comment by xiao623** [comment]
https://pypi.org/project/kidash/0.4.21/
